# Generated by Django 6.0.7 on 2026-08-04 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji yoki icon nomi', max_length=50)),
            ],
            options={
                'verbose_name': 'Tadbir kategoriyasi',
                'verbose_name_plural': 'Tadbir kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('venue_name', models.CharField(blank=True, max_length=255)),
                ('venue_address', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('total_capacity', models.PositiveIntegerField(default=0)),
                ('available_tickets', models.PositiveIntegerField(default=0)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Chop etilgan'), ('cancelled', 'Bekor qilingan'), ('sold_out', 'Chiptalar tugagan'), ('completed', "O'tib ketdi")], default='draft', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('tags', models.JSONField(default=list)),
                ('branch', models.ForeignKey(blank=True, help_text="Qaysi filialda o'tkaziladi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory')),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['status', 'starts_at'], name='events_even_status_5c3d55_idx'), models.Index(fields=['is_exclusive', 'status'], name='events_even_is_excl_f6c448_idx')],
            },
        ),
    ]
