# Generated by Django 5.1.4 on 2026-09-01 11:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_count', models.PositiveIntegerField(default=1, help_text='Chipta soni (max 10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan'), ('checked_in', 'Kelgan')], default='pending', max_length=20)),
                ('booking_reference', models.CharField(help_text='Bron raqami', max_length=50, unique=True)),
                ('special_requests', models.TextField(blank=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Tadbir ro'yxati",
                'verbose_name_plural': "Tadbir ro'yxatlari",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='events_even_event_i_cdd3f8_idx'), models.Index(fields=['user', 'status'], name='events_even_user_id_642524_idx'), models.Index(fields=['booking_reference'], name='events_even_booking_63b0e9_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
