# Generated by Django 5.1.4 on 2026-09-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_tickets',
            field=models.PositiveIntegerField(default=0, help_text='Qolgan chiptalar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_capacity',
            field=models.PositiveIntegerField(default=0, help_text="Umumiy sig'im"),
        ),
    ]
