# Generated by Django 6.0.7 on 2026-09-04 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceColor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text="Masalan: 'Binafsha', 'Ko'k'", max_length=50, verbose_name='Nomi (ixtiyoriy)')),
                ('hex_code', models.CharField(help_text='Masalan: #8B5CF6', max_length=7, unique=True)),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Ranglar',
                'ordering': ['name', 'hex_code'],
            },
        ),
        migrations.CreateModel(
            name='ServiceIcon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, help_text="Frontendda ishlatiladigan icon kaliti (masalan: 'plane', 'fork-knife', 'car')", unique=True)),
                ('svg', models.TextField(blank=True, help_text='SVG kod sifatida saqlash (ixtiyoriy)', null=True)),
                ('image', models.ImageField(blank=True, help_text='Rasm fayl sifatida saqlash (ixtiyoriy)', null=True, upload_to='service_icons/')),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Iconlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, help_text='Avtomatik name dan generatsiya qilinadi', unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami — pastroq raqam oldinroq chiqadi', verbose_name='Tartib')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecolor', verbose_name='Rang')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.serviceicon', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['is_active'], name='services_se_is_acti_91b7ea_idx'), models.Index(fields=['order'], name='services_se_order_8a41e4_idx'), models.Index(fields=['slug'], name='services_se_slug_4657d0_idx')],
            },
        ),
    ]
