# Generated by Django 6.0.7 on 2026-08-04 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProviderLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('aviakassa', 'Aviakassa'), ('railway', "Temir yo'l"), ('other', 'Boshqa')], max_length=30)),
                ('method', models.CharField(choices=[('search', 'Qidiruv'), ('get_price', 'Narx olish'), ('create_booking', 'Bron yaratish'), ('cancel_booking', 'Bron bekor qilish'), ('check_status', 'Holat tekshirish')], max_length=30)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('booking_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Tashqi API logi',
                'verbose_name_plural': 'Tashqi API loglari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'method', 'is_success'], name='integration_provide_2d3a3f_idx')],
            },
        ),
    ]
