# Generated by Django 6.0.7 on 2026-08-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalproviderlog',
            name='provider',
            field=models.CharField(choices=[('aviakassa', 'Aviakassa'), ('bookhara', 'Bookhara GDS'), ('railway', "Temir yo'l"), ('other', 'Boshqa')], max_length=30),
        ),
    ]
