# Generated by Django 5.1.4 on 2026-09-01 10:56

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMusic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('mood', models.CharField(choices=[('relaxing', 'Relaxing'), ('energetic', 'Energetic'), ('romantic', 'Romantic'), ('classical', 'Classical'), ('jazz', 'Jazz'), ('pop', 'Pop'), ('ambient', 'Ambient')], default='relaxing', max_length=20)),
                ('audio_file', models.FileField(help_text='Audio file (mp3, wav, ogg) - max 50MB', upload_to='music/tracks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])])),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Audio duration in seconds (auto-detected on upload)', null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one track can be active at a time')),
                ('volume', models.PositiveSmallIntegerField(default=70, help_text='Volume level (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('loop', models.BooleanField(default=True, help_text='Loop the track')),
                ('fade_in_seconds', models.PositiveSmallIntegerField(default=0, help_text='Fade in duration (seconds)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('fade_out_seconds', models.PositiveSmallIntegerField(default=0, help_text='Fade out duration (seconds)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for filtering')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fon musiqasi',
                'verbose_name_plural': 'Fon musiqalari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='music_backg_is_acti_bf8493_idx'), models.Index(fields=['mood'], name='music_backg_mood_a9181f_idx')],
            },
        ),
    ]
