# Generated by Django 5.1.4 on 2026-09-01 10:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0011_restaurantbooking_is_ai_generated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('flight', 'Parvoz'), ('restaurant', 'Restoran'), ('event', 'Tadbir'), ('hotel', 'Mehmonxona'), ('tour', 'Tur sayohat')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.PositiveSmallIntegerField(blank=True, help_text='Foiz chegirma (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Belgilangan chegirma (so'm)", max_digits=14, null=True)),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, help_text='Minimal buyurtma miqdori', max_digits=14)),
                ('max_usage_count', models.PositiveIntegerField(blank=True, help_text='Maksimal ishlatish soni (0=cheksiz)', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bonus kategoriyasi',
                'verbose_name_plural': 'Bonus kategoriyalari',
                'ordering': ['order', 'service_type', 'name'],
                'indexes': [models.Index(fields=['service_type', 'is_active'], name='bonuses_bon_service_b3bb76_idx'), models.Index(fields=['valid_from', 'valid_until'], name='bonuses_bon_valid_f_d7ff40_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBonus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code', models.CharField(help_text='Noyob QR kod identifikatori', max_length=255, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, help_text='QR kod rasm fayli', null=True, upload_to='qrcodes/bonuses/')),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('bonus_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bonuses', to='bonuses.bonuscategory')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_bonuses', to='booking.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi bonusi',
                'verbose_name_plural': 'Foydalanuvchi bonuslari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used'], name='bonuses_use_user_id_2abbb6_idx'), models.Index(fields=['qr_code'], name='bonuses_use_qr_code_7bcf12_idx')],
                'unique_together': {('user', 'bonus_category')},
            },
        ),
    ]
