# Generated by Django 5.1.4 on 2026-09-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0002_migrate_userbonus_to_qrcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBonus',
        ),
    ]
