# Generated by Django 6.0.7 on 2026-08-11 15:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0004_tourbooking_alter_booking_service_type'),
        ('crm', '0002_alter_organization_org_type_restauranttable_and_more'),
        ('membership', '0002_alter_membershiptier_commission_discount_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji yoki icon nomi', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tours/categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tur kategoriyasi',
                'verbose_name_plural': 'Tur kategoriyalari',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TourDestination',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=3)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tours/destinations/')),
                ('climate_info', models.TextField(blank=True, help_text='Iqlim haqida qisqacha')),
                ('visa_info', models.TextField(blank=True, help_text='Viza talablari')),
                ('best_months', models.JSONField(default=list, help_text='["June", "July", "August"] — eng yaxshi oylar')),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': "Sayohat yo'nalishi",
                'verbose_name_plural': "Sayohat yo'nalishlari",
                'ordering': ['-is_popular', 'name'],
                'unique_together': {('country', 'city')},
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tours/packages/')),
                ('gallery', models.JSONField(default=list, help_text='["https://...", "https://..."] — qo\'shimcha rasm URL lari')),
                ('duration_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_nights', models.PositiveSmallIntegerField(default=0)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('price_per', models.CharField(choices=[('person', 'Kishi boshiga'), ('group', 'Guruh uchun')], default='person', max_length=10)),
                ('max_group_size', models.PositiveSmallIntegerField(default=20)),
                ('min_group_size', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Bosh sahifada chiqarish')),
                ('is_exclusive', models.BooleanField(default=False, help_text="Faqat a'zolar uchun")),
                ('inclusions', models.JSONField(default=list, help_text='["Aviachipta", "Transfer", "Mehmonxona (2 kishilik)", "Nonushta"]')),
                ('exclusions', models.JSONField(default=list, help_text='["Viza xarajatlari", "Sug\'urta", "Shaxsiy xarajatlar"]')),
                ('requirements', models.JSONField(default=list, help_text='["Pasport (6 oy amal qilishi kerak)", "Tibbiy ko\'rik"]')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Oson'), ('moderate', "O'rta"), ('hard', 'Qiyin'), ('extreme', 'Ekstremal')], default='easy', max_length=10)),
                ('tags', models.JSONField(default=list, help_text='["beach", "family", "adventure", "budget"]')),
                ('languages_offered', models.JSONField(default=list, help_text='["uz", "ru", "en"] — gid tillari')),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_packages', to='crm.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='tours.tourcategory')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='tours.tourdestination')),
                ('exclusive_tier', models.ForeignKey(blank=True, help_text="Faqat shu tier va undan yuqori a'zolar ko'radi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusive_tours', to='membership.membershiptier')),
                ('organization', models.ForeignKey(limit_choices_to={'org_type': 'tour_company'}, on_delete=django.db.models.deletion.PROTECT, related_name='tour_packages', to='crm.organization')),
            ],
            options={
                'verbose_name': 'Tur paketi',
                'verbose_name_plural': 'Tur paketlari',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourItineraryDay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(help_text='1-kun: Toshkent → Dubai', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activities', models.JSONField(default=list, help_text='[{"time": "09:00", "activity": "Burj Khalifa ziyorati", "location": "Dubai"}]')),
                ('accommodation', models.CharField(blank=True, help_text='Mehmonxona nomi', max_length=255)),
                ('meals', models.JSONField(default=dict, help_text='{"breakfast": true, "lunch": false, "dinner": true}')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/itinerary/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='tours.tourpackage')),
            ],
            options={
                'verbose_name': 'Kun dasturi',
                'verbose_name_plural': 'Kun dasturlari',
                'ordering': ['package', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='TourAvailability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('total_seats', models.PositiveSmallIntegerField()),
                ('booked_seats', models.PositiveSmallIntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text="Asosiy narxdan farq qilsa shu maydon to'ldiriladi", max_digits=16, null=True)),
                ('status', models.CharField(choices=[('open', 'Bron uchun ochiq'), ('closed', 'Yopilgan'), ('waitlist', "Kutish ro'yxati"), ('cancelled', 'Bekor qilingan')], default='open', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('guide_name', models.CharField(blank=True, help_text='Guruh gidi ismi', max_length=150)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='tours.tourpackage')),
            ],
            options={
                'verbose_name': 'Tur mavjudligi',
                'verbose_name_plural': 'Tur mavjudliklari',
                'ordering': ['departure_date'],
            },
        ),
        migrations.CreateModel(
            name='TourReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField()),
                ('photos', models.JSONField(default=list, help_text='["https://...", ...] — sharh rasmlar URL lari')),
                ('is_verified', models.BooleanField(default=False, help_text='Haqiqiy bron asosida — avtomatik tekshiriladi')),
                ('is_published', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tourpackage')),
                ('tour_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='booking.tourbooking')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tur sharhi',
                'verbose_name_plural': 'Tur sharhlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourVoucher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_number', models.CharField(help_text="TUR-2026-00001 ko'rinishida avtomatik yaratiladi", max_length=30, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Faol'), ('used', 'Ishlatilgan'), ('expired', "Muddati o'tgan"), ('revoked', 'Bekor qilingan')], default='active', max_length=10)),
                ('package_snapshot', models.JSONField(default=dict, help_text="Paket ma'lumotlari snapshot: nomi, yo'nalishi, narxi, ...")),
                ('tourist_snapshot', models.JSONField(default=list, help_text="Sayohatchilar ro'yxati snapshot")),
                ('booking_snapshot', models.JSONField(default=dict, help_text="Bron ma'lumotlari: narx, sana, mehmonxona afzalligi, ...")),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='tours/vouchers/')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_vouchers', to=settings.AUTH_USER_MODEL)),
                ('tour_booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='voucher', to='booking.tourbooking')),
            ],
            options={
                'verbose_name': 'Tur voaucheri',
                'verbose_name_plural': 'Tur voaucherlari',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['organization', 'is_active'], name='tours_tourp_organiz_917407_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['destination', 'is_active'], name='tours_tourp_destina_f964d2_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['is_featured', 'is_active'], name='tours_tourp_is_feat_b6b84b_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['category', 'is_active'], name='tours_tourp_categor_de4c9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='touritineraryday',
            unique_together={('package', 'day_number')},
        ),
        migrations.AddIndex(
            model_name='touravailability',
            index=models.Index(fields=['package', 'departure_date', 'status'], name='tours_toura_package_b870b0_idx'),
        ),
        migrations.AddIndex(
            model_name='tourreview',
            index=models.Index(fields=['package', 'is_published', 'rating'], name='tours_tourr_package_e824fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tourreview',
            unique_together={('package', 'user')},
        ),
    ]
