# Generated by Django 5.1.4 on 2026-09-03 03:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_destination_org_and_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touravailability',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Asosiy narxdan farq qilsa shu maydon to'ldiriladi", max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
