# Generated by Django 5.1.4 on 2026-09-01 10:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_uz', models.CharField(blank=True, help_text='Uzbek name', max_length=100)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 code (e.g., UZ, TR)', max_length=3, unique=True)),
                ('flag_emoji', models.CharField(blank=True, help_text='Country flag emoji', max_length=10)),
                ('currency', models.CharField(blank=True, help_text='Currency code (e.g., USD, EUR)', max_length=10)),
                ('calling_code', models.CharField(blank=True, help_text='Phone calling code (e.g., +998)', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mamlakat',
                'verbose_name_plural': 'Mamlakatlar',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['code'], name='destination_code_5a8663_idx'), models.Index(fields=['is_active'], name='destination_is_acti_e69c4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(blank=True, help_text='Uzbek name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('description_uz', models.TextField(blank=True, help_text='Uzbek description')),
                ('category', models.CharField(choices=[('city', 'Shahar'), ('beach', 'Dengiz sohili'), ('mountain', "Tog'"), ('historical', 'Tarixiy joy'), ('nature', 'Tabiat'), ('adventure', 'Sarguzasht'), ('cultural', 'Madaniyat'), ('modern', 'Zamonaviy')], default='city', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (0-5)', max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_popular', models.BooleanField(default=False, help_text='Popular destination')),
                ('is_active', models.BooleanField(default=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='destinations/featured/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='destinations.country')),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
                'ordering': ['-is_popular', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='destinations/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('caption_uz', models.CharField(blank=True, help_text='Uzbek caption', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image for destination')),
                ('order', models.PositiveIntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Manzil rasmi',
                'verbose_name_plural': 'Manzil rasmlari',
                'ordering': ['-is_primary', 'order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['country', 'is_active'], name='destination_country_926a74_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['category'], name='destination_categor_7c9900_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['is_popular'], name='destination_is_popu_9f121a_idx'),
        ),
        migrations.AddIndex(
            model_name='destinationimage',
            index=models.Index(fields=['destination', 'is_primary'], name='destination_destina_d9abf1_idx'),
        ),
    ]
