# Generated by Django 6.0.7 on 2026-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='featured_image_thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail', null=True, upload_to='destinations/featured/thumbnails/'),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated thumbnail', null=True, upload_to='destinations/images/thumbnails/'),
        ),
    ]
