# Generated by Django 6.0.7 on 2026-09-04 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_rebuild_destination_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='destination',
            new_name='destination_group_924f05_idx',
            old_name='destination_group_idx',
        ),
        migrations.RenameIndex(
            model_name='destination',
            new_name='destination_is_acti_09f11c_idx',
            old_name='destination_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='destination',
            new_name='destination_code_ae319e_idx',
            old_name='destination_code_idx',
        ),
        migrations.AlterField(
            model_name='destination',
            name='flag_image',
            field=models.ImageField(blank=True, help_text='Bayroq rasmi', null=True, upload_to='destinations/flags/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='group',
            field=models.CharField(choices=[('popular', 'Популярные'), ('signature', 'IMTIAZ Signature')], default='popular', help_text='Популярные yoki IMTIAZ Signature', max_length=20),
        ),
    ]
