# Generated by Django 5.1.4 on 2026-09-03 03:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_featured_image_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90.00')), django.core.validators.MaxValueValidator(Decimal('90.00'))]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180.00')), django.core.validators.MaxValueValidator(Decimal('180.00'))]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))]),
        ),
    ]
