# Generated by Django 6.0.7 on 2026-08-11 15:46

import apps.qr_codes.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0004_tourbooking_alter_booking_service_type'),
        ('crm', '0002_alter_organization_org_type_restauranttable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=apps.qr_codes.models._generate_qr_code, help_text='URL-safe noyob kod', max_length=20, unique=True)),
                ('qr_image', models.ImageField(blank=True, help_text='Avtomatik generatsiya qilingan PNG', null=True, upload_to='qr_codes/images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('qr_type', models.CharField(choices=[('discount_percent', 'Foiz chegirma (%)'), ('discount_fixed', "Belgilangan chegirma (so'm)"), ('bonus_points', 'Bonus ball'), ('free_service', 'Bepul xizmat')], max_length=25)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text="15.00 (foiz uchun 15%), 50000.00 (so'm uchun)", max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Foiz chegirma uchun maksimal sum chegarasi', max_digits=14, null=True)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimal buyurtma miqdori', max_digits=14)),
                ('applicable_services', models.JSONField(default=list, help_text='["tour", "restaurant", "all"] — qaysi xizmatga tegishli')),
                ('max_total_uses', models.PositiveIntegerField(blank=True, help_text="Jami necha marta qo'llanishi mumkin (null = cheksiz)", null=True)),
                ('max_uses_per_user', models.PositiveSmallIntegerField(default=1, help_text='Bir foydalanuvchi necha marta ishlatishi mumkin')),
                ('total_used_count', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='crm.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qr_codes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='crm.organization')),
            ],
            options={
                'verbose_name': 'QR Kod',
                'verbose_name_plural': 'QR Kodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRAnalyticsSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('apply_count', models.PositiveIntegerField(default=0)),
                ('reject_count', models.PositiveIntegerField(default=0)),
                ('total_discount_given', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='qr_codes.qrcode')),
            ],
            options={
                'verbose_name': 'QR Analitika (kunlik)',
                'verbose_name_plural': 'QR Analitikalar (kunlik)',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeRedemption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(blank=True, help_text='tour, restaurant, general', max_length=20)),
                ('order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('scanned', 'Skanerlandi'), ('applied', "Qo'llandi"), ('rejected', 'Rad etildi'), ('expired', "Muddati o'tgan")], default='scanned', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_redemptions', to='booking.booking')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='qr_codes.qrcode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "QR Qo'llash",
                'verbose_name_plural': "QR Qo'llashlar",
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['code'], name='qr_codes_qr_code_16f2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['organization', 'is_active'], name='qr_codes_qr_organiz_00ebcf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qranalyticssummary',
            unique_together={('qr_code', 'date')},
        ),
        migrations.AddIndex(
            model_name='qrcoderedemption',
            index=models.Index(fields=['qr_code', 'user', 'scanned_at'], name='qr_codes_qr_qr_code_4f797b_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcoderedemption',
            index=models.Index(fields=['status', 'scanned_at'], name='qr_codes_qr_status_238e80_idx'),
        ),
    ]
