# Generated by Django 5.1.4 on 2026-09-04 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0001_initial'),
        ('crm', '0010_alter_branch_latitude_alter_branch_longitude_and_more'),
        ('qr_codes', '0002_qrcoderedemption_customer_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa — OMMAVIY kampaniya (hamma skanerlay oladi). To'ldirilgan bo'lsa — faqat shu foydalanuvchiga tegishli SHAXSIY vaucher.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_qr_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='service_type',
            field=models.CharField(choices=[('flight', 'Parvoz'), ('restaurant', 'Restoran'), ('event', 'Tadbir'), ('hotel', 'Mehmonxona'), ('tour', 'Tur sayohat'), ('all', 'Barcha xizmatlar')], db_index=True, default='all', help_text="Qaysi xizmat turiga tegishli — mobil ilovada bo'lim bo'yicha filtrlash uchun", max_length=20),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text="Qaysi umumiy bonus e'lonidan (shablon) yaratilgani — ixtiyoriy", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='bonuses.bonuscategory'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa — IMTIAZ platforma darajasidagi umumiy bonus (tashkilotga bog'lanmagan)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='crm.organization'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['assigned_user', 'is_active'], name='qr_codes_qr_assigne_169de1_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['service_type', 'is_active'], name='qr_codes_qr_service_b285de_idx'),
        ),
    ]
