# Generated by Django 5.1.4 on 2026-09-01 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_tourlead_restaurantlead_customer_analysis'),
        ('crm_restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantStaff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('manager', 'Menejer'), ('staff', 'Xodim')], default='staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_staff', to='crm.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restoran xodimi',
                'verbose_name_plural': 'Restoran xodimlari',
                'unique_together': {('user', 'restaurant')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantBookingLead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('party_size', models.PositiveSmallIntegerField(help_text='Nechta kishi')),
                ('preferred_time', models.TimeField(help_text='Tanlangan vaqt (HH:MM)')),
                ('restaurant_type', models.CharField(choices=[('casual', 'Casual'), ('fine_dining', 'Fine Dining'), ('fast_food', 'Fast Food'), ('delivery', 'Delivery')], default='casual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan'), ('customer_negotiating', 'Mijoz bilan muzokara'), ('confirmed', 'Tasdiqlangan')], db_index=True, default='pending', max_length=30)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('actual_time', models.TimeField(blank=True, help_text='Muzokaradan keyingi haqiqiy vaqt', null=True)),
                ('notes', models.TextField(blank=True, help_text='Xodim izohlari')),
                ('special_requests', models.TextField(blank=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_leads', to='crm.branch')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_booking_leads', to='crm_restaurant.restaurantstaff')),
            ],
            options={
                'verbose_name': 'Restoran bron leadi',
                'verbose_name_plural': 'Restoran bron leadlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'status'], name='crm_restaur_restaur_fb1b00_idx'), models.Index(fields=['status', 'created_at'], name='crm_restaur_status_fb5167_idx')],
            },
        ),
    ]
