# Generated by Django 6.0.7 on 2026-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_restaurant', '0002_restaurantstaff_restaurantbookinglead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantbookinglead',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan'), ('customer_negotiating', 'Mijoz bilan muzokara'), ('confirmed', 'Tasdiqlangan'), ('expired', 'Muddati tugagan')], db_index=True, default='pending', max_length=30),
        ),
    ]
