# Generated by Django 5.1.4 on 2026-09-01 11:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('setting_type', models.CharField(choices=[('ai_assistant_name', 'AI Assistant Name'), ('company_name', 'Company Name'), ('support_phone', 'Support Phone'), ('support_email', 'Support Email'), ('currency', 'Default Currency'), ('timezone', 'Default Timezone')], max_length=30)),
                ('description', models.TextField(blank=True, help_text='Setting description')),
                ('is_public', models.BooleanField(default=False, help_text='Can be accessed by public API')),
            ],
            options={
                'verbose_name': 'Ilova sozlamasi',
                'verbose_name_plural': 'Ilova sozlamalari',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key'], name='settings_ap_key_514ee7_idx'), models.Index(fields=['setting_type'], name='settings_ap_setting_f77809_idx')],
            },
        ),
    ]
