# Generated by Django 6.0.7 on 2026-08-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_externa_77ac9f_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='external_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('multicard', 'Multicard'), ('wallet', 'IMTIAZ Hamyon')], help_text="To'lov provayderi — hali tanlanmagan, stub bilan ishlaydi", max_length=20),
        ),
    ]
