# Generated by Django 6.0.7 on 2026-08-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_payments_pa_externa_77ac9f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('multicard', 'Multicard'), ('wallet', 'IMTIAZ Hamyon'), ('alifpay', 'AlifPay')], help_text="To'lov provayderi — hali tanlanmagan, stub bilan ishlaydi", max_length=20),
        ),
    ]
