# Generated by Django 6.0.7 on 2026-08-08 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=64, null=True)),
                ('role', models.CharField(choices=[('customer', 'Mijoz'), ('owner', 'Tashkilot egasi'), ('branch_staff', 'Filial xodimi'), ('admin', 'Admin')], db_index=True, default='customer', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('language_code', models.CharField(default='uz', max_length=10)),
                ('is_phone_verified', models.BooleanField(default=False, help_text="SMS OTP orqali tasdiqlangan (register 2-qadamida True bo'ladi)")),
                ('ai_autonomy_level', models.CharField(choices=[('manual', "Qo'lda tasdiqlash (har bir harakatda)"), ('semi_auto', 'Yarim avtomatik (yuqori summada tasdiqlash)'), ('full_auto', "To'liq avtomatik")], default='manual', max_length=20)),
                ('ai_auto_price_limit', models.DecimalField(decimal_places=2, default=500000, help_text='full_auto uchun maksimal avtomatik bron summasi (UZS)', max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bonus_points', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('purpose', models.CharField(choices=[('register', "Ro'yxatdan o'tish"), ('password_reset', 'Parolni tiklash')], default='register', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'OTP Kod',
                'verbose_name_plural': 'OTP Kodlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'purpose', 'is_used', 'expires_at'], name='users_otpco_phone_159373_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile (Flutter)'), ('telegram', 'Telegram Mini App'), ('web_crm', 'Web CRM'), ('web_admin', 'Web Admin')], max_length=20)),
                ('refresh_token_jti', models.CharField(help_text='JWT refresh tokenning JTI claim qiymati', max_length=255, unique=True)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi qurilmasi',
                'verbose_name_plural': 'Foydalanuvchi qurilmalari',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('topup', "To'ldirish"), ('payment', "To'lov"), ('refund', 'Qaytarish'), ('bonus_earn', "Bonus yig'ish"), ('bonus_spend', 'Bonus sarflash')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_id', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hamyon operatsiyasi',
                'verbose_name_plural': 'Hamyon operatsiyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_user_phone_9474e8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_id'], name='users_user_telegra_b51e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'is_active'], name='users_userd_user_id_a5f926_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['refresh_token_jti'], name='users_userd_refresh_95449e_idx'),
        ),
    ]
