# Generated by Django 6.0.7 on 2026-08-04 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=64, null=True)),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('language_code', models.CharField(default='ru', max_length=10)),
                ('ai_autonomy_level', models.CharField(choices=[('manual', "Qo'lda tasdiqlash (har bir harakatda)"), ('semi_auto', 'Yarim avtomatik (yuqori summada tasdiqlash)'), ('full_auto', "To'liq avtomatik")], default='manual', max_length=20)),
                ('ai_auto_price_limit', models.DecimalField(decimal_places=2, default=500000, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bonus_points', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('topup', "To'ldirish"), ('payment', "To'lov"), ('refund', 'Qaytarish'), ('bonus_earn', "Bonus yig'ish"), ('bonus_spend', 'Bonus sarflash')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_id', models.CharField(blank=True, help_text="Tashqi to'lov ID", max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hamyon operatsiyasi',
                'verbose_name_plural': 'Hamyon operatsiyalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
