# Generated by Django 6.0.7 on 2026-08-11 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_tourbooking_alter_booking_service_type'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('restaurant', 'Restoran'), ('airline', 'Aviakompaniya'), ('railway', "Temir yo'l"), ('event_organizer', 'Tadbir tashkilotchisi'), ('hotel', 'Mehmonxona'), ('tour_company', 'Tur kompaniyasi'), ('other', 'Boshqa')], max_length=30),
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_number', models.CharField(help_text='"A1", "VIP-3", "Teras-5"', max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(help_text='Necha kishilik')),
                ('min_capacity', models.PositiveSmallIntegerField(default=1)),
                ('section', models.CharField(blank=True, help_text='"Teras", "Ichki zal", "VIP xona"', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('features', models.JSONField(default=list, help_text='["window_view", "outdoor", "smoking", "projector"]')),
                ('current_status', models.CharField(choices=[('available', "Bo'sh"), ('reserved', 'Bron qilingan'), ('occupied', 'Band'), ('maintenance', "Ta'mirda")], default='available', max_length=20)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='crm.branch')),
            ],
            options={
                'verbose_name': 'Restoran stoli',
                'verbose_name_plural': 'Restoran stollar',
                'ordering': ['branch', 'section', 'table_number'],
                'unique_together': {('branch', 'table_number')},
            },
        ),
        migrations.CreateModel(
            name='StaffActivityLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('confirm_tour_booking', 'Tur bronini tasdiqlash'), ('reject_tour_booking', 'Tur bronini rad etish'), ('generate_voucher', 'Voaucher yaratish'), ('confirm_table_booking', 'Stol bronini tasdiqlash'), ('cancel_table_booking', 'Stol bronini bekor qilish'), ('update_table_status', 'Stol holatini yangilash'), ('add_table', "Stol qo'shish"), ('login', 'Tizimga kirish'), ('logout', 'Tizimdan chiqish'), ('view_analytics', "Analitikani ko'rish"), ('manage_qr', 'QR kod boshqarish'), ('manage_packages', 'Paketlarni boshqarish')], max_length=50)),
                ('entity_type', models.CharField(blank=True, help_text='Qaysi model: TourBooking, RestaurantBooking, ...', max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='crm.branchstaff')),
            ],
            options={
                'verbose_name': 'Xodim faoliyat jurnali',
                'verbose_name_plural': 'Xodim faoliyat jurnallari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['staff', 'action_type', 'created_at'], name='crm_staffac_staff_i_c9ce47_idx'), models.Index(fields=['entity_type', 'entity_id'], name='crm_staffac_entity__555b27_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffPerformanceSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('tour_bookings_confirmed', models.PositiveIntegerField(default=0)),
                ('tour_bookings_rejected', models.PositiveIntegerField(default=0)),
                ('vouchers_generated', models.PositiveIntegerField(default=0)),
                ('table_bookings_confirmed', models.PositiveIntegerField(default=0)),
                ('table_bookings_cancelled', models.PositiveIntegerField(default=0)),
                ('total_revenue_managed', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('avg_response_time_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('total_actions', models.PositiveIntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_summaries', to='crm.branchstaff')),
            ],
            options={
                'verbose_name': "Xodim ish ko'rsatkichlari",
                'verbose_name_plural': "Xodim ish ko'rsatkichlari",
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['staff', 'period_type', 'period_start'], name='crm_staffpe_staff_i_7fa42c_idx')],
                'unique_together': {('staff', 'period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='TableTimeSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_slots', to='booking.restaurantbooking')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='crm.restauranttable')),
            ],
            options={
                'verbose_name': 'Stol vaqt sloti',
                'verbose_name_plural': 'Stol vaqt slotlari',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['table', 'date', 'is_available'], name='crm_tableti_table_i_0a21aa_idx')],
            },
        ),
    ]
