# Generated by Django 5.1.4 on 2026-08-13 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_aiactionlog_expires_at'),
        ('crm', '0003_organization_business_type_and_owner'),
        ('tours', '0002_destination_org_and_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='crm_webhook_secret',
            field=models.CharField(blank=True, help_text="Webhook so'roviga X-Signature sifatida qo'shiladigan maxfiy kalit (HMAC-SHA256). Hamkor CRM tomonidan so'rov haqiqiyligini tekshirish uchun.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='crm_webhook_url',
            field=models.URLField(blank=True, help_text="Hamkorning tashqi CRM tizimi lead qabul qiluvchi endpointi. Bo'sh bo'lsa — lead faqat IMTIAZ ichida (TourLead jadvalida) saqlanadi.", null=True),
        ),
        migrations.CreateModel(
            name='TourLead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('preferred_departure_date', models.DateField(blank=True, null=True)),
                ('passengers', models.PositiveSmallIntegerField(default=1)),
                ('note', models.TextField(blank=True, help_text="Mijoz bildirgan qo'shimcha talablar")),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('sent', 'CRM ga yuborildi'), ('failed', 'Yuborishda xato'), ('contacted', "Mijoz bilan bog'lanildi"), ('converted', 'Bronga aylandi'), ('declined', 'Rad etildi')], default='new', max_length=12)),
                ('crm_response', models.JSONField(blank=True, default=dict, help_text='Hamkor CRM javobi (debug uchun)')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('organization', models.ForeignKey(limit_choices_to={'org_type': 'tour_company'}, on_delete=django.db.models.deletion.CASCADE, related_name='tour_leads', to='crm.organization')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='tours.tourpackage')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_leads', to='ai_assistant.conversationsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tur lead',
                'verbose_name_plural': 'Tur leadlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='crm_tourlea_organiz_5496bb_idx'), models.Index(fields=['phone'], name='crm_tourlea_phone_14b53f_idx')],
            },
        ),
    ]
