# Generated by Django 5.1.4 on 2026-08-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_organization_crm_webhook_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('restaurant', 'Restoran'), ('bakery', 'Peykari / Kofe'), ('wellness', 'Wellness / Yoga'), ('sport', 'Sport / Padel'), ('fashion', 'Fashion / Kiyim'), ('kids', 'Bolalar mahsulotlari'), ('lifestyle', 'Lifestyle / Concept'), ('fitness', 'Fitnes / Zallar'), ('tech', 'Texnologiya / Gadjetlar'), ('parfum', 'Parfyumeriya / Kosmetika'), ('airline', 'Aviakompaniya'), ('railway', "Temir yo'l"), ('event_organizer', 'Tadbir tashkilotchisi'), ('hotel', 'Mehmonxona'), ('tour_company', 'Tur kompaniyasi'), ('other', 'Boshqa')], max_length=30),
        ),
    ]
