# Generated by Django 5.1.4 on 2026-08-20 05:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_aiactionlog_duration_ms_aiactionlog_request_id_and_more'),
        ('crm', '0005_alter_organization_org_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantLead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('guests', models.PositiveSmallIntegerField(default=2)),
                ('note', models.TextField(blank=True, help_text="Mijoz bildirgan qo'shimcha so'rovlar")),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('sent', 'CRM ga yuborildi'), ('failed', 'Yuborishda xato'), ('contacted', "Mijoz bilan bog'lanildi"), ('confirmed', 'Stol bronlandi'), ('declined', 'Rad etildi')], default='new', max_length=12)),
                ('crm_response', models.JSONField(blank=True, default=dict, help_text='Hamkor CRM javobi')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_leads', to='crm.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_leads', to='crm.organization')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_leads', to='ai_assistant.conversationsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restoran lead',
                'verbose_name_plural': 'Restoran leadlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='crm_restaur_organiz_169c35_idx'), models.Index(fields=['phone'], name='crm_restaur_phone_e50d23_idx')],
            },
        ),
    ]
