# Generated by Django 6.0.7 on 2026-08-21 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_aiactionlog_duration_ms_aiactionlog_request_id_and_more'),
        ('crm', '0006_restaurantlead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('travel', 'Sayohatlar'), ('restaurant', 'Stol band qilish'), ('roadside', "Yo'lda yordam"), ('medical', 'Tibbiyot'), ('insurance', "Sug'urta"), ('family_office', 'Family Office'), ('leisure', 'Dam olish'), ('flight', 'Parvoz bileti'), ('other', 'Boshqa xizmat')], db_index=True, default='other', max_length=30)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('service_name', models.CharField(blank=True, help_text="So'ralgan xizmat nomi", max_length=255)),
                ('customer_analysis', models.TextField(blank=True, help_text='AI tomonidan mijoz haqida yozilgan tahliliy tavsif')),
                ('note', models.TextField(blank=True, help_text="Mijoz so'rovining to'liq tafsilotlari")),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('sent', 'CRM / Telegram ga yuborildi'), ('failed', 'Yuborishda xato'), ('contacted', "Mijoz bilan bog'lanildi"), ('converted', 'Bajarildi'), ('declined', 'Rad etildi')], default='new', max_length=12)),
                ('crm_response', models.JSONField(blank=True, default=dict, help_text='Yuborish javobi')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_leads', to='crm.organization')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_leads', to='ai_assistant.conversationsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xizmat leadi',
                'verbose_name_plural': 'Xizmat leadlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'status'], name='crm_service_categor_b09cdf_idx'), models.Index(fields=['phone'], name='crm_service_phone_1a999b_idx')],
            },
        ),
    ]
