# Generated by Django 5.1.4 on 2026-08-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_servicelead'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlead',
            name='assigned_staff_name',
            field=models.CharField(blank=True, help_text="Lead bo'yicha shug'ullanayotgan xodim ismi/username", max_length=150),
        ),
        migrations.AddField(
            model_name='servicelead',
            name='assigned_staff_name',
            field=models.CharField(blank=True, help_text="Lead bo'yicha shug'ullanayotgan xodim ismi/username", max_length=150),
        ),
        migrations.AddField(
            model_name='tourlead',
            name='assigned_staff_name',
            field=models.CharField(blank=True, help_text="Lead bo'yicha shug'ullanayotgan xodim ismi/username", max_length=150),
        ),
    ]
