# Generated by Django 5.1.4 on 2026-08-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_restaurantlead_assigned_staff_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlead',
            name='customer_analysis',
            field=models.TextField(blank=True, help_text='AI tomonidan suhbat tarixidan yaratilgan mijoz tahlili'),
        ),
        migrations.AddField(
            model_name='tourlead',
            name='customer_analysis',
            field=models.TextField(blank=True, help_text='AI tomonidan suhbat tarixidan yaratilgan mijoz tahlili'),
        ),
    ]
