# Generated by Django 5.1.4 on 2026-09-03 04:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_tourlead_restaurantlead_customer_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90.00')), django.core.validators.MaxValueValidator(Decimal('90.00'))]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180.00')), django.core.validators.MaxValueValidator(Decimal('180.00'))]),
        ),
        migrations.AlterField(
            model_name='staffperformancesummary',
            name='avg_response_time_minutes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='staffperformancesummary',
            name='total_revenue_managed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
