# Generated by Django 5.1.4 on 2026-09-03 03:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0002_destination_featured_image_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedTrip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Masalan: "IMTIAZ Dubai Luxury"', max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text='Masalan: "Дубай + сафари по пустыне"', max_length=255)),
                ('short_description', models.CharField(blank=True, help_text='Kartochkada ko\'rinadigan qisqa matn: "Роскошь, шопинг и незабываемые приключения..."', max_length=500)),
                ('full_description', models.TextField(blank=True, help_text="Detail sahifada to'liq matn")),
                ('cover_image', models.ImageField(help_text="Video ustida play tugmasi bilan ko'rinadigan asosiy rasm — MAJBURIY", upload_to='travel_content/curated_trips/covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('video_file', models.FileField(help_text="MAJBURIY — bu model uchun video har doim bo'lishi shart (image-only variant yo'q)", upload_to='travel_content/curated_trips/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'webm'])])),
                ('duration_days_min', models.PositiveSmallIntegerField(help_text='Masalan 4 ("4-6 kun" bo\'lsa)', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_days_max', models.PositiveSmallIntegerField(help_text='Masalan 6', validators=[django.core.validators.MinValueValidator(1)])),
                ('group_size_min', models.PositiveSmallIntegerField(default=1)),
                ('group_size_max', models.PositiveSmallIntegerField(default=2, help_text='Kartochkada ko\'rsatiladigan odam soni (masalan "2 kishi")')),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price_unit', models.CharField(choices=[('route', 'Marshrut uchun'), ('person', 'Kishi boshiga')], default='route', max_length=10)),
                ('is_verified_by_imtiaz', models.BooleanField(default=True, help_text='"Проверено командой IMTIAZ" belgisini ko\'rsatish/yashirish')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text="Bosh sahifada tepada ko'rsatiladimi")),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_trips', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'IMTIAZ Travels — kuratsiyalangan tur',
                'verbose_name_plural': 'IMTIAZ Travels — kuratsiyalangan turlar',
                'ordering': ['sort_order', '-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CuratedTripImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='travel_content/curated_trips/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='travel_content.curatedtrip')),
            ],
            options={
                'verbose_name': 'Kuratsiyalangan tur galereya rasmi',
                'verbose_name_plural': 'Kuratsiyalangan tur galereya rasmlari',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelReel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Masalan: "St. Moritz"', max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text='Qisqa tagline — kartochkada ko\'rinadi. Masalan: "Зима, лыжи и стиль"', max_length=255)),
                ('description', models.TextField(blank=True, help_text="To'liq matn — reels fullscreen ochilganda ko'rsatiladi")),
                ('media_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video')], default='image', max_length=5)),
                ('cover_image', models.ImageField(help_text='MAJBURIY — kartochka/thumbnail rasmi (video post uchun ham kerak)', upload_to='travel_content/reels/covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('video_file', models.FileField(blank=True, help_text="media_type='video' bo'lganda MAJBURIY", null=True, upload_to='travel_content/reels/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'webm'])])),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text="Kichik raqam — birinchi ko'rsatiladi")),
                ('destination', models.ForeignKey(blank=True, help_text="Ixtiyoriy — qaysi manzilga tegishli ekanini bog'lash uchun", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Sayohat ilhomi (Reel)',
                'verbose_name_plural': 'Sayohat ilhomlari (Reels)',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='curatedtrip',
            index=models.Index(fields=['is_active', 'sort_order'], name='travel_cont_is_acti_899428_idx'),
        ),
        migrations.AddIndex(
            model_name='travelreel',
            index=models.Index(fields=['is_active', 'sort_order'], name='travel_cont_is_acti_272516_idx'),
        ),
    ]
