# Generated by Django 5.1.4 on 2026-09-03 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_content', '0002_alter_curatedtrip_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedtripimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travel_content/curated_trips/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
