# Generated by Django 5.1.4 on 2026-09-03 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_content', '0003_alter_curatedtripimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedtrip',
            name='cover_image',
            field=models.ImageField(help_text="Video ustida play tugmasi bilan ko'rinadigan asosiy rasm — MAJBURIY", upload_to='travel_content/curated_trips/covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='curatedtrip',
            name='video_file',
            field=models.FileField(default=3, help_text="MAJBURIY — bu model uchun video har doim bo'lishi shart (image-only variant yo'q)", upload_to='travel_content/curated_trips/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'webm'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelreel',
            name='cover_image',
            field=models.ImageField(help_text='MAJBURIY — kartochka/thumbnail rasmi (video post uchun ham kerak)', upload_to='travel_content/reels/covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
