# Generated by Django 5.1.4 on 2026-09-03 03:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_content', '0004_alter_curatedtrip_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedtrip',
            name='price_from',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
