# Generated by Django 5.1.4 on 2026-09-01 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInquiry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('general', 'Umumiy'), ('booking', 'Bron'), ('payment', "To'lov"), ('technical', 'Texnik'), ('account', 'Hisob'), ('feedback', 'Fikr-mulohaza')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rtacha"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('in_progress', 'Jarayonda'), ('resolved', 'Hal qilingan'), ('closed', 'Yopiq')], default='open', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('admin_response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('responded_by', models.ForeignKey(blank=True, help_text='Admin who responded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_inquiries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Foydalanuvchi so'rovi",
                'verbose_name_plural': "Foydalanuvchi so'rovlari",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='support_use_user_id_ba03ae_idx'), models.Index(fields=['status', 'priority'], name='support_use_status_494831_idx'), models.Index(fields=['category'], name='support_use_categor_14c2a6_idx')],
            },
        ),
    ]
