# Generated by Django 6.0.7 on 2026-08-04 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_ai_autonomy_level', models.CharField(choices=[('manual', "Qo'lda tasdiqlash (har bir harakatda)"), ('semi_auto', 'Yarim avtomatik (yuqori summada tasdiqlash)'), ('full_auto', "To'liq avtomatik")], default='semi_auto', max_length=20)),
                ('commission_discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Booking narxidan chegirma foizi', max_digits=5)),
                ('exclusive_events_access', models.BooleanField(default=False, help_text='Eksklyuziv tadbirlarga kirish huquqi')),
                ('priority_support', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': "A'zolik darajasi",
                'verbose_name_plural': "A'zolik darajalari",
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='membership.membershiptier')),
            ],
            options={
                'verbose_name': 'Promo-kod',
                'verbose_name_plural': 'Promo-kodlar',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('past_due', "To'lov muddati o'tgan"), ('cancelled', 'Bekor qilingan'), ('trial', 'Sinov davri')], default='active', max_length=20)),
                ('card_token', models.CharField(blank=True, max_length=255, null=True)),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('started_at', models.DateTimeField()),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('last_payment_attempt', models.DateTimeField(blank=True, null=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='membership.membershiptier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('promo_code', models.CharField(blank=True, max_length=32, null=True)),
                ('notes', models.TextField(blank=True, help_text='Ariza izohlar (foydalanuvchi tomonidan)')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin izohi (ichki)')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waitlist arizasi',
                'verbose_name_plural': 'Waitlist arizalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
