# Generated by Django 6.0.7 on 2026-08-04 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptier',
            name='commission_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Booking narxidan chegirma foizi (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='membershiptier',
            name='exclusive_events_access',
            field=models.BooleanField(default=False, help_text='Eksklyuziv tadbirlarga kirish'),
        ),
        migrations.AlterField(
            model_name='waitlistapplication',
            name='notes',
            field=models.TextField(blank=True, help_text='Foydalanuvchi izohi'),
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_ai_autonomy_level', models.CharField(default='manual', max_length=20)),
                ('exclusive_events_access', models.BooleanField(default=False)),
                ('commission_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='membership.membershiptier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership_tier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Foydalanuvchi a'zoligi",
                'verbose_name_plural': "Foydalanuvchilar a'zoligi",
            },
        ),
    ]
