# Generated by Django 5.1.4 on 2026-09-03 03:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_membershiptier_commission_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptier',
            name='commission_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Booking narxidan chegirma foizi (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='membershiptier',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='commission_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
