# Generated by Django 6.0.7 on 2026-08-04 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('crm', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('flight', 'Parvoz'), ('train', 'Poyezd'), ('restaurant', 'Restoran'), ('event', 'Tadbir'), ('hotel', 'Mehmonxona')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan'), ('completed', 'Bajarilgan'), ('refunded', 'Qaytarilgan'), ('failed', 'Amalga oshmadi')], default='pending', max_length=20)),
                ('title', models.CharField(help_text='Bron nomi (masalan: MSQ→DXB, Nobu restoran)', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('booking_date', models.DateTimeField(blank=True, help_text='Bron amalga oshiriladigan vaqt', null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('external_booking_id', models.CharField(blank=True, max_length=128, null=True)),
                ('external_provider', models.CharField(blank=True, max_length=64, null=True)),
                ('created_by_ai', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('ai_action_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='ai_assistant.aiactionlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bron',
                'verbose_name_plural': 'Bronlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_count', models.PositiveSmallIntegerField(default=1)),
                ('ticket_type', models.CharField(blank=True, max_length=50)),
                ('seat_info', models.CharField(blank=True, max_length=100, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_detail', to='booking.booking')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event')),
            ],
            options={
                'verbose_name': 'Tadbir broni',
                'verbose_name_plural': 'Tadbir bronlari',
            },
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(help_text='IATA kodi, masalan TAS', max_length=3)),
                ('destination', models.CharField(help_text='IATA kodi, masalan DXB', max_length=3)),
                ('departure_at', models.DateTimeField()),
                ('arrival_at', models.DateTimeField(blank=True, null=True)),
                ('airline', models.CharField(blank=True, max_length=64)),
                ('flight_number', models.CharField(blank=True, max_length=20)),
                ('seat_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First')], default='economy', max_length=20)),
                ('passenger_count', models.PositiveSmallIntegerField(default=1)),
                ('baggage_included', models.BooleanField(default=False)),
                ('pnr_code', models.CharField(blank=True, help_text='Locator / PNR', max_length=20, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_detail', to='booking.booking')),
            ],
            options={
                'verbose_name': 'Parvoz broni',
                'verbose_name_plural': 'Parvoz bronlari',
            },
        ),
        migrations.CreateModel(
            name='RestaurantBooking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_at', models.DateTimeField()),
                ('guest_count', models.PositiveSmallIntegerField(default=2)),
                ('special_requests', models.TextField(blank=True)),
                ('table_number', models.CharField(blank=True, max_length=20, null=True)),
                ('confirmed_by_staff', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_detail', to='booking.booking')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_bookings', to='crm.branch')),
            ],
            options={
                'verbose_name': 'Restoran broni',
                'verbose_name_plural': 'Restoran bronlari',
            },
        ),
        migrations.CreateModel(
            name='TrainBooking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_station', models.CharField(max_length=100)),
                ('destination_station', models.CharField(max_length=100)),
                ('departure_at', models.DateTimeField()),
                ('arrival_at', models.DateTimeField(blank=True, null=True)),
                ('train_number', models.CharField(blank=True, max_length=20)),
                ('wagon_type', models.CharField(choices=[('platzkart', 'Platzkart'), ('coupe', 'Kupe'), ('sv', 'SV'), ('sitting', "O'tirish")], default='coupe', max_length=20)),
                ('seat_number', models.CharField(blank=True, max_length=10, null=True)),
                ('passenger_count', models.PositiveSmallIntegerField(default=1)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='train_detail', to='booking.booking')),
            ],
            options={
                'verbose_name': 'Poyezd broni',
                'verbose_name_plural': 'Poyezd bronlari',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='booking_boo_user_id_dddf68_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service_type', 'status'], name='booking_boo_service_d45357_idx'),
        ),
    ]
