# Generated by Django 6.0.7 on 2026-08-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='provider_response',
            field=models.JSONField(blank=True, help_text="Provayderdan kelgan to'liq xom JSON javob", null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='provider_status',
            field=models.CharField(blank=True, help_text='Provayderdan kelgan xom status (masalan: ticketed, awaitpayment)', max_length=30),
        ),
    ]
