# Generated by Django 6.0.7 on 2026-08-10 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_flightbooking_provider_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_type', models.IntegerField(default=0)),
                ('ikpu_provider_1', models.CharField(blank=True, max_length=32)),
                ('package_code_prov1', models.CharField(blank=True, max_length=32)),
                ('id_provider_1', models.CharField(blank=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nds_provider_1', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ikpu_bookhara', models.CharField(blank=True, max_length=32)),
                ('package_code_bkh', models.CharField(blank=True, max_length=32)),
                ('service_fee_bkh', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nds_bookhara', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('receipt_url', models.URLField(blank=True)),
                ('flight_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.flightbooking')),
            ],
            options={
                'verbose_name': "Parvoz to'lovi (fiskal)",
                'verbose_name_plural': "Parvoz to'lovlari (fiskal)",
                'ordering': ['-created_at'],
            },
        ),
    ]
