# Generated by Django 6.0.7 on 2026-08-11 15:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_flightpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tourist_count', models.PositiveSmallIntegerField(default=1)),
                ('tourists_info', models.JSONField(default=list, help_text='[{"name": "Ism Familiya", "passport": "AC123456", "dob": "1990-01-01", "nationality": "UZ"}]')),
                ('special_requests', models.TextField(blank=True)),
                ('hotel_preference', models.CharField(choices=[('standard', 'Standart'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('any', 'Farq qilmaydi')], default='any', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('operator_notes', models.TextField(blank=True)),
                ('voucher_generated', models.BooleanField(default=False)),
                ('voucher_generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tur broni',
                'verbose_name_plural': 'Tur bronlari',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('flight', 'Parvoz'), ('train', 'Poyezd'), ('restaurant', 'Restoran'), ('event', 'Tadbir'), ('hotel', 'Mehmonxona'), ('tour', 'Tur sayohat')], max_length=20),
        ),
    ]
