# Generated by Django 6.0.7 on 2026-08-11 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_tourbooking_alter_booking_service_type'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_bookings', to='tours.touravailability'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour_detail', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tour_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_bookings', to='tours.tourpackage'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='voucher_generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tour_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tourbooking',
            index=models.Index(fields=['package', 'availability'], name='booking_tou_package_18e20e_idx'),
        ),
        migrations.AddIndex(
            model_name='tourbooking',
            index=models.Index(fields=['voucher_generated'], name='booking_tou_voucher_c01662_idx'),
        ),
    ]
