# Generated by Django 6.0.7 on 2026-08-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_tourbooking_ai_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan'), ('completed', 'Bajarilgan'), ('refunded', 'Qaytarilgan'), ('failed', 'Amalga oshmadi')], default='pending', max_length=20),
        ),
    ]
