# Generated by Django 6.0.7 on 2026-08-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_settlement_saga'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookingsettlement',
            new_name='booking_boo_status_c3d3c5_idx',
            old_name='booking_set_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='bookingtransactionlog',
            new_name='booking_boo_settlem_10a85d_idx',
            old_name='booking_tx_settlement_step_idx',
        ),
        migrations.AlterField(
            model_name='bookingsettlement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookingtransactionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
