# Generated by Django 5.1.4 on 2026-09-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_booking_set_status_created_idx_booking_boo_status_c3d3c5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantbooking',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='AI orqali yaratlganmi'),
        ),
        migrations.AddField(
            model_name='restaurantbooking',
            name='preferred_time',
            field=models.TimeField(blank=True, help_text='Tanlangan vaqt (HH:MM)', null=True),
        ),
        migrations.AddField(
            model_name='restaurantbooking',
            name='restaurant_type',
            field=models.CharField(choices=[('casual', 'Casual'), ('fine_dining', 'Fine Dining'), ('fast_food', 'Fast Food'), ('delivery', 'Delivery')], default='casual', help_text='Restoran turi', max_length=20),
        ),
    ]
