# Generated by Django 6.0.7 on 2026-08-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0002_lead'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_core_le_organiz_5dbea6_idx',
            old_name='crm_core_le_org_vert_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='crm_core_le_organiz_1ed698_idx',
            old_name='crm_core_le_org_created_idx',
        ),
    ]
