# Generated by Django 6.0.7 on 2026-08-04 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Avto-yaratilgan sarlavha', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('context_summary', models.TextField(blank=True, help_text='Uzoq sessiyalar uchun kontekst qisqartmasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suhbat sessiyasi',
                'verbose_name_plural': 'Suhbat sessiyalari',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('assistant', 'AI'), ('system', 'Tizim')], max_length=20)),
                ('content', models.TextField()),
                ('tool_calls', models.JSONField(blank=True, help_text='Claude tool_use bloklari', null=True)),
                ('tool_results', models.JSONField(blank=True, help_text='Tool natijalar', null=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.conversationsession')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIActionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('search', 'Qidiruv'), ('recommend', 'Tavsiya'), ('book', 'Bron qilish'), ('cancel', 'Bekor qilish'), ('payment_confirm', "To'lovni tasdiqlash"), ('payment_initiate', "To'lovni boshlash"), ('info_request', "Ma'lumot so'rash")], max_length=30)),
                ('service_type', models.CharField(blank=True, max_length=20, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Muvaffaqiyatli'), ('failed', 'Amalga oshmadi'), ('needs_confirmation', 'Tasdiqlash kerak'), ('cancelled_by_user', 'Foydalanuvchi bekor qildi')], default='success', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('amount_requiring_confirmation', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_action_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='ai_assistant.conversationsession')),
            ],
            options={
                'verbose_name': 'AI harakat logi',
                'verbose_name_plural': 'AI harakat loglari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action_type', 'created_at'], name='ai_assistan_user_id_fcb8f5_idx'), models.Index(fields=['status', 'created_at'], name='ai_assistan_status_9f50ad_idx')],
            },
        ),
    ]
