# Generated by Django 6.0.7 on 2026-08-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiactionlog',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='needs_confirmation holati uchun muddat (5 daqiqa)', null=True),
        ),
    ]
