# Generated by Django 6.0.7 on 2026-08-15 14:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_aiactionlog_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAIProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_seat_class', models.CharField(blank=True, max_length=20)),
                ('preferred_cuisine', models.CharField(blank=True, max_length=100)),
                ('frequent_destinations', models.JSONField(blank=True, default=list)),
                ('summary_text', models.TextField(blank=True, help_text="AI tomonidan yozilgan qisqa xulosa (session'larni chetlab, doimiy profil)")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI foydalanuvchi profili',
                'verbose_name_plural': 'AI foydalanuvchi profillari',
            },
        ),
    ]
