# Generated by Django 6.0.7 on 2026-08-15 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_useraiprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiactionlog',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Ushbu harakat necha millisekund davom etgani', null=True),
        ),
        migrations.AddField(
            model_name='aiactionlog',
            name='request_id',
            field=models.CharField(blank=True, default='', help_text="HTTP so'rov request_id (logging_middleware bilan bogʻlash uchun)", max_length=36),
        ),
        migrations.AddIndex(
            model_name='aiactionlog',
            index=models.Index(fields=['request_id'], name='ai_assistan_request_58ec24_idx'),
        ),
    ]
