# Generated by Django 5.1.4 on 2026-09-04 04:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Название', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Краткое описание')),
                ('image_url', models.URLField(blank=True, help_text='Фото URL')),
                ('link', models.CharField(choices=[('/ai', 'Imtiaz AI'), ('/services/tours', 'Туры'), ('/services/travel', 'Путешествия'), ('/services/restaurant', 'Рестораны'), ('/events', 'События'), ('/bonuses', 'Бонусы')], help_text='Ссылка (dropdown)', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Banner tartibi')),
                ('is_active', models.BooleanField(default=True, help_text='Faollik')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='banners_ban_is_acti_2fb269_idx')],
            },
        ),
    ]
