# Generated by Django 6.0.7 on 2026-08-04 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('booking_confirmed', 'Bron tasdiqlandi'), ('booking_cancelled', 'Bron bekor qilindi'), ('payment_success', "To'lov muvaffaqiyatli"), ('payment_failed', "To'lov amalga oshmadi"), ('booking_reminder', 'Bron eslatmasi'), ('ai_suggestion', 'AI taklifi'), ('subscription_renewal', 'Obuna yangilandi'), ('subscription_past_due', "Obuna to'lovi o'tmadi"), ('waitlist_approved', "A'zolik tasdiqlandi"), ('general', 'Umumiy')], max_length=40)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('push', 'Push bildirishnoma'), ('in_app', 'Ilova ichida')], default='telegram', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Navbatda'), ('sent', 'Yuborildi'), ('failed', 'Amalga oshmadi'), ('read', "O'qildi")], default='pending', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_7088ed_idx'), models.Index(fields=['status', 'scheduled_at'], name='notificatio_status_a9c93f_idx')],
            },
        ),
    ]
