# Generated by Django 5.1.4 on 2026-09-04 04:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_branch_latitude_alter_branch_longitude_and_more'),
        ('notifications', '0002_notification_new_lead_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Bron tasdiqlandi'), ('booking_cancelled', 'Bron bekor qilindi'), ('payment_success', "To'lov muvaffaqiyatli"), ('payment_failed', "To'lov amalga oshmadi"), ('booking_reminder', 'Bron eslatmasi'), ('ai_suggestion', 'AI taklifi'), ('subscription_renewal', 'Obuna yangilandi'), ('subscription_past_due', "Obuna to'lovi o'tmadi"), ('waitlist_approved', "A'zolik tasdiqlandi"), ('new_lead', 'Yangi lead (CRM)'), ('promo_discount', 'Chegirma taklifi'), ('qr_scan_success', 'QR skan muvaffaqiyatli'), ('general', 'Umumiy')], max_length=40),
        ),
        migrations.CreateModel(
            name='PromoDiscount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_phone', models.CharField(help_text='Mijoz telefon raqami', max_length=20)),
                ('customer_name', models.CharField(blank=True, help_text='Mijoz ismi (ixtiyoriy)', max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Foiz'), ('fixed', "Qat'iy summa")], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Foiz yoki summa', max_digits=12)),
                ('title', models.CharField(help_text='Chegirma sarlavhasi', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Chegirma tavsifi')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Chegirma muddati', null=True)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=20)),
                ('is_sent', models.BooleanField(default=False, help_text='Bildirishnoma yuborildi')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promos', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_discounts', to='crm.organization')),
            ],
            options={
                'verbose_name': 'Chegirma taklifi',
                'verbose_name_plural': 'Chegirma takliflari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='notificatio_organiz_ddec6c_idx'), models.Index(fields=['customer_phone', 'status'], name='notificatio_custome_330132_idx')],
            },
        ),
    ]
